name: Setup
description: Setup Build Step
inputs:
  node-version:
    required: true
    default: '18.x'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    # Wireit cache
    - uses: google/wireit@setup-github-actions-caching/v1

    - name: Install dependencies
      shell: bash
      run: pnpm install
