name: Chromatic

on:
  push:
    branches:
      - main
  deployment_status:

jobs:
  playwright:
    name: Playwright Tests with Chromatic on ${{ github.event.deployment_status.environment }}
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Output Run Number
        run: echo "RUN_ID=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        
      - name: Install Test Dependencies
        run: pnpm install
      
      - name: Install Playwright
        run: pnpm playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: ./playwright-report
          retention-days: 30

  chromatic:
    name: Run Chromatic
    needs: playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Download Playwright test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-results
          path: ./playwright-report
          
      - name: Run Chromatic
        uses: FormidableLabs/chromaui-action@latest
        with:
          playwright: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    
  