name: Chromatic

# Runs chromatic on:
#   every pull request where there are changes in stories/ or packages/ and the PR is not in draft mode
on:
  pull_request:
    branches:
      - main
    paths:
      - "stories/**"

jobs:
  chromatic:
    name: Storybook Publish
    if: github.event.pull_request.draft == false && github.repository == 'FormidableLabs/victory'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Get Yarn Cache Directory Path
        id: cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Set Yarn to Ignore Engines
        run: yarn config set ignore-engines true

      - name: Installation
        run: yarn --prefer-offline --frozen-lockfile --non-interactive

      - name: Build Package Libs
        run: yarn nps build-package-libs

      - name: Build Storybook
        run: yarn build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Remove Yarn Config to Ignore Engines
        run: yarn config delete ignore-engines
